
dx = [0, 0, 1, -1]
dy = [1, -1, 0, 0]

GRASS_SCORE = 1
BREAD_SCORE = 1

MIN_DEFENDERS = 6
MIN_EXPLORERS = 2
MIN_GATHER_ANTS = 4
MIN_WORKER_ANTS = 8

MIN_ATTACKING_SOLDIERS = 7

MAX_HEALTH_WORKER = 4
MAX_HEALTH_SOLDIER = 6

MAX_DEVIATION_RADIUS = 4

MIN_CARRY_FOR_ANT = 5
MAX_CARRY_AMOUNT = 10
MAX_CHANGE_IDEA_COUNT = 2

MAX_AGENT_VIEW_DISTANCE = 4
MAX_ATTACK_DISTANCE_SOLDIER = 4

UNKNOWN_DISTANCE_PENALTY = 3

DEFEND_RADIUS = 7

GREEDYNESS_HARVEST_FACTOR = 2.5

GATHERING_PORTION = 4

FORCE_ATTACK_TURN = 150

STAND_RADIUS_FROM_ENEMY_BASE = 8

BASE_ATTACK_DISTANCE = 6

DEFENDERS_IN_LAYER = 6